# Generated by Django 3.1.7 on 2021-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210418_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
