# Generated by Django 3.1.7 on 2021-04-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210424_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientList',
            new_name='IngredientRecipe',
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Ингредиент-Рецепт', 'verbose_name_plural': 'Ингредиенты-Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
