# Generated by Django 3.1.7 on 2021-04-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210424_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Ингредиенты-Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Ингредиент-Рецепт', 'verbose_name_plural': 'Ингредиенты-Рецепты'},
        ),
    ]
